### ISSUE TITLE
Why worker.js in scc-broker?

### ISSUE THREAD

**Issue by malfusion** [SocketCluster/sc-cluster-broker-server#10]
In the guide over at "https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md" it says

> The scc-broker service can be made up of any number of scc-broker instances - This is a special backend-only service which is designed to broker messages between multiple frontend-facing socketcluster instances. All the pub/sub channels in your entire system will be sharded evenly across available scc-broker instances. Just like with the socketcluster instances above, each scc-broker instance needs to point to a state server in order to work.

And the diagram shows that workers are part of the 'socketcluster' instances.

1. Then why does an 'scc-broker' instance also contain a worker.js? 
2. Isn't the job of an 'scc-broker' only to be a broker (broker.js) and not a worker?
3. If the 'scc-broker' instances do provide a httpworker, is the http workload balanced between the 'socketcluster' and the 'scc-broker' instances. 
4. Is it optional to have worker.js in 'scc-broker' instances. 

Can you please clarify this?

**Comment by jondubois** [comment]
@malfusion Every component of SCC is a specialized SocketCluster instance. The scc-broker can be scaled up just like a regular user-facing SC instance so yes, the scc-broker also has local worker and broker processes.

SCC's horizontal scaling/sharding strategy across multiple machines is essentially the same as its vertical scaling strategy within a single machine so that's why the concepts seem recursive. It wasn't absolutely necessary to do it that way; we could have restricted the scc-broker to a single process and just add more of them but we would lose efficiency for certain scenarios. With the current design, a single machine is able to share messages internally across all of its CPU cores rather than always going over the network... It kind of behaves like a cache for realtime messages for the whole machine.
