### ISSUE TITLE
Publish v6.0.2 to npmjs

### ISSUE THREAD

**Issue by toredash** [SocketCluster/sc-cluster-broker-server#16]
v6.0.2 isnt published to npmjs

**Comment by MegaGM** [comment]
v6.0.2 was the last version based internally on SocketCluster v14
Currently latest `scc-broker` in npm is v7, which is based internally on SocketCluster v15 but, IIRC (don't quote me on that), `scc-broker` v7 should be externally compatible with SocketCluster <=14, as long as you use `scc-broker-client` and `scc-state` of the same major version.
But anyway [SCC Guide](https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md) recommends cloning `scc-state` and `scc-broker` Github repos instead of installing from npm.
